spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yontaverse
    username: teemyroom
    password: teemyroom4321
  jpa:
    hibernate:
      ddl-auto: update

security:
  enabled: false

logging:
  level:
    root: info
